### ISSUE TITLE
[Suggestion] link to your post

### ISSUE THREAD

**Issue by erkobridee** [manakuro/visual-regression-testing-with-chromatic-example#9]
Hi there, just a suggestion, it would be nice to have a link on your README.md back to your post 
https://betterprogramming.pub/automating-ui-feedback-and-visual-testing-in-web-applications-d91f687a2840

I came here from there.

Best regards,
Erko  Bridee

**Comment by manakuro** [comment]
Hi @erkobridee, thanks for your suggestion! I've added the link to the About and README.md.
